language: node_js

node_js:
  - 10

cache:
  npm: true
  directories:
    - ~/.cache

 before_install:
   - stty cols 80

dist: trusty
sudo: required

env:
  - SAUCE_USERNAME="Atadeno"
  - SAUCE_ACCESS_KEY="6eb2505f-25a7-4992-8347-026fdca62d15"
  - SAUCE_JOB="E2E TestCafe Val"
  - SAUCE_BUILD="Build 2"

install:
  - npm install
  - npm install codeclimate-test-reporter istanbul -g

addons:
    code_climate:
        repo_token: "205cebb02c01600fc4764ac1270d5e0632f3724887045b00a762ba718ad0452c"

after_success: npm run coverage