language: node_js

node_js:
  - 10

cache:
  npm: true
  directories:
    - ~/.cache

dist: trusty
sudo: required

env:
   global:
     - SAUCE_JOB="TestCafe Val"

install:
  - npm install
  - npm install codeclimate-test-reporter istanbul -g

addons:
    code_climate:
        repo_token: "205cebb02c01600fc4764ac1270d5e0632f3724887045b00a762ba718ad0452c"


#after_success: npm run coverage