language: node_js

node_js:
  - 10

cache:
  npm: true
  directories:
    - ~/.cache

dist: trusty
sudo: required

# env:
#   global:
#     - SAUCE_USERNAME="Atadeno"
#     - SAUCE_ACCESS_KEY="ab506a56-14c8-4166-b204-85827a276c59"

install:
  - npm install
  - npm install codeclimate-test-reporter istanbul -g

addons:
    code_climate:
        repo_token: "205cebb02c01600fc4764ac1270d5e0632f3724887045b00a762ba718ad0452c"
    sauce_connect: true

after_success: npm run coverage


  